### PR TITLE
Add AgentDescription::newRTCFunctionFile()

### PR DESCRIPTION
**Pull request by Robadob**
Loads RTC function string from file.

Have checked the new tests pass.

### CODE REVIEW

**Review by ptheywood — APPROVED** [review]
Looks fine to me, but not tested it myself.  

I wonder if this has any potential impact on rtc debugging (i.e. breakpoints are attached to functions by name? Though lines will be 2 out compared to what is atually compiled anyway)

**Comment by Robadob** [comment]
> Looks fine to me, but not tested it myself.
> 
> I wonder if this has any potential impact on rtc debugging (i.e. breakpoints are attached to functions by name? Though lines will be 2 out compared to what is atually compiled anyway)

RTC debugging depends on whatever filename is told to jitify. So this won't work for that.

Lines should only be 1 out in this format (the header include). They're normally an extra out, because the opening quote is on a line by itself.

**Comment by ptheywood** [comment]
Isn't the other line the `program` name that gets inserted rather than just a blank new line at the start of the string? 
Eitherway, this should make the development experience nicer (although users may need to add the `#include "flamegpu/runtime/DeviceAPI.h"` themselves for autocompletions depending on editor?).

**Comment by Robadob** [comment]
> Isn't the other line the program name that gets inserted rather than just a blank new line at the start of the string?

Mm possibly, though i'm not aware of the input string being trimmed.


> (although users may need to add the #include "flamegpu/runtime/DeviceAPI.h" themselves for autocompletions depending on editor?).

Yes

**Pull request merged**
