### PR TITLE
Fix use of id_t in boids examples

### PR DESCRIPTION
**Pull request by ptheywood**

### CODE REVIEW

**Comment by Robadob** [comment]
Is there even a reason why Boids isn't using proper ID? rather than a manual variable?

**Comment by ptheywood** [comment]
It is, but messages do not have an automatic ID?

**Comment by Robadob** [comment]
Ah, that's my misunderstanding. I only skim read the changelog. Should be fine then.

**Review by Robadob — APPROVED** [review]
Python example was already fixed (just looked).

**Pull request merged**
