### PR TITLE
Change the default number of Simulation steps to 1

### LINKED ISSUE #634: Set -s/--steps default to 1
The current default of running forever by default is bad form

### PR DESCRIPTION
**Pull request by ptheywood**
Closes #634

### CODE REVIEW

**Review by Robadob — APPROVED** [review]
Looks good.

Thought you'd said, would leave it 0 for vis, but the consistency like this is probably better.

**Comment by ptheywood** [comment]
Paul suggested that he preferred consistency during the meeting (If I remember correctly). 

Users can still programatically override the default value themselves `#ifdef VISUALISATION` if required. 
If the vis default were different too it would have some interesting behaviour with the vis build but run as console flag, should it be 0 or 1 in that case etc.

**Comment by Robadob** [comment]
Yeah, it would need a fancy workaround that tracks arg parsing etc, to change it if not set and --console passed.

**Comment by Robadob** [comment]
Don't worry, merge it. Will just have to change my muscle memory for running examples.

**Pull request merged**
