### PR TITLE
Extend logging to allow inclusion of timing data.

### PR DESCRIPTION
**Pull request by Robadob**
Users are able to request time is included in the step or exit log, if either is selected a performance specs struct will be included in the log side besides config. Should work with ensemble logs too (these use a slightly different method to include `RunPlan` data).

The step log for step 0 includes the init function time.
The exit log only contains the full simulation time.

Exit function time, RTC layer time are never logged.

Also several bug fixes, see the individual commits.

### CODE REVIEW

**Comment by Robadob** [comment]
Appears the Ubuntu failures are in test_logging_exceptions, so will leave those till I get onto the tests.

**Comment by Robadob** [comment]
*Note, the `performance_specs` block is only included if step/exit time is requested.*

Step/Exit logs look like this

```js
{
	"config": {
		"random_seed": 1644933028
	},
	"performance_specs": {
		"device_name": "NVIDIA GeForce GTX 1080",
		"device_cc_major": 6,
		"device_cc_minor": 1,
		"cuda_version": 11040,
		"seatbelts": true,
		"flamegpu_version": "2.0.0-alpha.3+57965108"
	},
	"steps": [
		{
			"step_index": 0,
			"time": 0.0
		},
		{
			"step_index": 2,
			"time": 0.11100000143051148
		}
	],
	"exit": {
		"step_index": 10,
		"time": 1.149999976158142
	}
}

```

Ensemble step log looks like this (albeit normally minified)

```js
{
	"config": {
		"random_seed": 0,
		"steps": 10,
		"environment": {
			"instance_id": 0
		}
	},
	"performance_specs": {
		"device_name": "NVIDIA GeForce GTX 1080",
		"device_cc_major": 6,
		"device_cc_minor": 1,
		"cuda_version": 11040,
		"seatbelts": true,
		"flamegpu_version": "2.0.0-alpha.3+57965108"
	},
	"steps": [{
		"step_index": 0,
		"time": 0.0,
		"agents": {
			"Agent1": {
				"default": {
					"count": 101,
					"variables": {
						"float_var": {
							"mean": 50.0,
							"standard_deviation": 29.154759474226503,
							"min": 0.0,
							"max": 100.0,
							"sum": 5050.0
						},
						"int_var": {
							"mean": 51.0,
							"standard_deviation": 29.154759474226503,
							"min": 1,
							"max": 101,
							"sum": 5151
						},
						"uint_var": {
							"mean": 52.0,
							"standard_deviation": 29.154759474226503,
							"min": 2,
							"max": 102,
							"sum": 5252
						}
					}
				}
			}
		}
	}, {
		"step_index": 2,
		"time": 0.10899999737739563,
		"agents": {
			"Agent1": {
				"default": {
					"count": 101,
					"variables": {
						"float_var": {
							"mean": 52.0,
							"standard_deviation": 29.154759474226503,
							"min": 2.0,
							"max": 102.0,
							"sum": 5252.0
						},
						"int_var": {
							"mean": 53.0,
							"standard_deviation": 29.154759474226503,
							"min": 3,
							"max": 103,
							"sum": 5353
						},
						"uint_var": {
							"mean": 54.0,
							"standard_deviation": 29.154759474226503,
							"min": 4,
							"max": 104,
							"sum": 5454
						}
					}
				}
			}
		}
	}]
}
```

**Comment by Robadob** [comment]
XML ensemble step looks like

```xml
<log>
    <config>
        <random_seed>0</random_seed>
        <steps>10</steps>
        <environment>
            <instance_id>1</instance_id>
        </environment>
    </config>
    <performance_specs>
        <device_name>NVIDIA GeForce GTX 1080</device_name>
        <device_cc_major>6</device_cc_major>
        <device_cc_minor>1</device_cc_minor>
        <cuda_version>11040</cuda_version>
        <seatbelts>true</seatbelts>
        <flamegpu_version>2.0.0-alpha.3+99fe9d27</flamegpu_version>
    </performance_specs>
    <steps>
        <step>
            <time>0</time>
        </step>
        <step>
            <time>0.1080000028014183</time>
        </step>
    </steps>
</log>
```

**Comment by Robadob** [comment]
Have decided to amend, so that step 0 contains the init layer (and RTC?) time. May also add exit layer time as a 2nd time to exit log.

**Comment by Robadob** [comment]
From discussing with Pete, split out exit log frame so it inherits the common rather than is the common. Then give it all the available timing things (except step timing list).

**Comment by Robadob** [comment]
Have now made these changes and updated the above examples in comments.

**Review by mondus — APPROVED** [review]
Needs adding to the user guide

**Pull request merged**
